# Generated by Django 3.2.3 on 2021-06-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingstep',
            name='model',
        ),
        migrations.AddField(
            model_name='stateworkingpiece',
            name='model',
            field=models.CharField(choices=[('IAS-Logo', 'Model of the IAS-logo')], default='IAS-Logo', max_length=100),
        ),
    ]
