# Generated by Django 3.2.3 on 2021-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingplan',
            name='workingSteps',
            field=models.ManyToManyField(blank=True, to='mesapi.WorkingStep'),
        ),
    ]
