# Generated by Django 3.2.3 on 2021-05-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('resourceId', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('bufferIn', models.BooleanField(default=False)),
                ('bufferOut', models.BooleanField(default=False)),
                ('bufInONo', models.PositiveSmallIntegerField(default=0)),
                ('bufInOPos', models.PositiveSmallIntegerField(default=0)),
                ('bufOutONo', models.PositiveSmallIntegerField(default=0)),
                ('bufOutOPos', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='stateplc',
            name='buffIn',
        ),
        migrations.RemoveField(
            model_name='stateplc',
            name='buffOut',
        ),
        migrations.AddField(
            model_name='stateplc',
            name='buffer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mesapi.buffer'),
        ),
    ]
