# Generated by Django 3.2.3 on 2021-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='storage',
        ),
        migrations.AlterField(
            model_name='workingstep',
            name='operationNo',
            field=models.PositiveSmallIntegerField(choices=[(510, 'Manual work'), (213, 'release a defined part on stopper 2'), (210, 'store a part from stopper 1')], default=510),
        ),
    ]
