# Generated by Django 3.2.3 on 2021-06-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedorder',
            name='assigendWorkingPlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mesapi.workingplan'),
        ),
        migrations.AlterField(
            model_name='assignedorder',
            name='assignedWorkingPiece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mesapi.stateworkingpiece'),
        ),
        migrations.AlterField(
            model_name='assignedorder',
            name='orderPos',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
