# Generated by Django 3.2.3 on 2021-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0002_auto_20210627_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateworkingpiece',
            name='isAssembled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stateworkingpiece',
            name='isPackaged',
            field=models.BooleanField(default=False),
        ),
    ]
