# Generated by Django 3.2.3 on 2021-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0002_auto_20210602_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingstep',
            name='operationNo',
            field=models.PositiveSmallIntegerField(choices=[(510, 'Manual work'), (213, 'release a defined part on stopper 2'), (210, 'store a part from stopper 1'), (1110, 'delay')], default=510),
        ),
    ]
