# Generated by Django 3.2.3 on 2021-06-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0002_auto_20210623_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedorder',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignedorder',
            name='orderNo',
            field=models.PositiveIntegerField(),
        ),
    ]
