# Generated by Django 3.2.3 on 2021-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0002_auto_20210517_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingstep',
            name='workingPlan',
        ),
        migrations.AddField(
            model_name='workingplan',
            name='workingSteps',
            field=models.ManyToManyField(null=True, to='mesapi.WorkingStep'),
        ),
    ]
