# Generated by Django 3.2.3 on 2021-06-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0003_auto_20210628_1733'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workingstep',
            unique_together={('id', 'stepNo')},
        ),
    ]
