# Generated by Django 3.2.3 on 2021-06-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0003_auto_20210623_1847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedorder',
            unique_together={('orderNo', 'orderPos')},
        ),
    ]
