# Generated by Django 3.2.3 on 2021-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0003_auto_20210531_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingstep',
            name='model',
            field=models.CharField(choices=[('IAS-Logo', 'Model of the IAS-logo')], default='IAS-Logo', max_length=100),
        ),
    ]
