# Generated by Django 3.2.3 on 2021-06-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0003_alter_workingstep_operationno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buffer',
            name='bufferIn',
        ),
        migrations.RemoveField(
            model_name='buffer',
            name='bufferOut',
        ),
    ]
