# Generated by Django 3.2.3 on 2021-06-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0004_alter_workingstep_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='useFleetmanager',
            field=models.BooleanField(default=True),
        ),
    ]
