# Generated by Django 3.2.3 on 2021-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0004_alter_workingplan_workingsteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedorder',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
