# Generated by Django 3.2.3 on 2021-05-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0005_assignedorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedorder',
            name='assigendWorkingPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesapi.workingplan'),
        ),
    ]
