# Generated by Django 3.2.3 on 2021-07-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0005_setting_usefleetmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
