# Generated by Django 3.2.3 on 2021-07-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0006_alter_costumer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='ipAdressMES4',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='isInBridgingMode',
        ),
    ]
