# Generated by Django 3.2.3 on 2021-07-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0007_auto_20210705_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='assignedorder',
            old_name='costumer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='costumerNo',
            new_name='customerNo',
        ),
    ]
