# Generated by Django 3.2.3 on 2021-05-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesapi', '0008_alter_workingplan_workingsteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingplan',
            name='workingSteps',
            field=models.ManyToManyField(to='mesapi.WorkingStep'),
        ),
    ]
